#!/bin/sh

#exec i3
 exec startkde

xrdb -merge ~/.Xresources

#if [ -s ~/.Xmodmap ]; then
 #   xmodmap ~/.Xmodmap
#fi

#setxkbmap us
#xmodmap ~/Descargas/colemak-1.0/xmodmap/xmodmap.colemak && xset r 66

#cd ~/Documentos/Development/Programs\ finished/Change\ xinitrc\ to\ i3/
#./Change_xinitrc_to_i3

#startx -- :1 &

#cd ~/Documentos/Development/Programs\ finished/Change\ xinitrc\ to\ kde/
#./Change_xinitrc_to_kde

